### ISSUE TITLE
Add instructions for creating a PostGIS extension in OVA

### ISSUE THREAD

**Issue by Zak-Kent** [hackoregon/getting-started#2]
Instructions for adding PostGIS extension

**Comment by znmeb** [comment]
No reason for instructions - it can be done in the code with calls to "psql" via "su - postgres -c"

**Comment by znmeb** [comment]
In next-gen-vm branch

**Comment by znmeb** [comment]
Install script now:
1. Creates a database superuser with the same ID as the person who ran the script. For example, in the Vagrant box the user is 'vagrant', so there's a PostgreSQL user named 'vagrant'.
2. Creates a personal database with that name. In the example, there's a 'vagrant' database.
3. Adds the extensions `plpython3u`, `postgis`, `postgis_topology` and `pgrouting` to that database.

**Comment by znmeb** [comment]
closing - in master branch
