### ISSUE TITLE
Make an alias for Jupyter in OVA

### ISSUE THREAD

**Issue by znmeb** [hackoregon/getting-started#3]

**Comment by scottslewis** [comment]
suggestion:   alias jupyternb='jupyter notebook --ip 0.0.0.0 --no-browser'

**Comment by znmeb** [comment]
That works ... I'm also thinking 'ads' and 'dds' for activate and deactivate data science - assuming those don't conflict with anything else.

**Comment by znmeb** [comment]
in next-gen-vm branch

**Comment by znmeb** [comment]
closing - in master branch
