### ISSUE TITLE
Prep for Vagrant

### ISSUE THREAD

**Issue by sanjuroj** [hackoregon/getting-started#8]
If it's possible to prepare the VM image for use as a Vagrant Box, some people might prefer to use Vagrant.  It sounds like Ed already has a script to do it, but just in case, there are instructions [here](https://www.vagrantup.com/docs/virtualbox/boxes.html).

**Comment by znmeb** [comment]
I've got the code for this done - I abandoned it in the throes of troubleshooting the VirtualBox issues on my workstation.

**Comment by znmeb** [comment]
Code is in branch `next-gen-vm`.

**Comment by znmeb** [comment]
Done ... see https://github.com/hackoregon/getting-started/blob/master/datascience/linux-laptop-setup/Using_the_Vagrant_Box.md for how to test it!
